ingress:
  controller:
    hostNetwork: true
    service:
      type: "ClusterIP"
mysql:
  fullnameOverride: "mysql"
  persistence:
    enabled: false
  primary:
    persistence:
      enabled: false
  secondary:
    persistence:
      enabled: false
  auth:
    rootPassword: 
    database: wordpress_app_database
    username: 
    password: 
  service:
    type: ClusterIP
phpmyadmin:
  ingress:
    enabled: true
    hostname: 
    path: "/phpmyadmin(/|$)(.*)"
    pathType: Prefix
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite ^(/dbadmin)$ $1/ permanent;
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
  db:
    host: "mysql"
    port: "3306"
  service:
    type: "ClusterIP"
#  extraEnvVars:
#    - name: "PHPMYADMIN_ABSOLUTE_URI"
#      value: "http://word.raeisi.org/phpmyadmin/"
wordpress:
  ingress:
    enabled: true
    hostname: 
    path: "/wordpress(/|$)(.*)"
    pathType: Prefix
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite ^(/wordpress)$ $1/ permanent;
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
  persistence:
    enabled: false
  mariadb:
    enabled: false
  externalDatabase:
    host: "mysql"
    port: 3306
    user: 
    password: 
    database: wordpress_app_database
  wordpressUsername: 
  wordpressPassword: 
  service:
    type: ClusterIP
  customPostInitScripts:
   change-wordpress-url.sh: |
     #!/bin/bash
     chmod +w /bitnami/wordpress/wp-config.php
     sed -i -r "s|_SERVER\['HTTP_HOST'\] \. '/'|_SERVER\['HTTP_HOST'\] \. '/wordpress/'|g" /bitnami/wordpress/wp-config.php
     chmod -w /bitnami/wordpress/wp-config.php

  link-wp: |
     #!/bin/bash
     ln -s /opt/bitnami/wordpress /opt/bitnami/wordpress/wordpress
     

